### ISSUE TITLE
SSL Cert Problem

### ISSUE THREAD

**Issue by tankerkiller125** [castle/castle-php#7]
After trying to login Castle will though a CURL error related to the SSL Chain having a Self Signed Cert in it. To be specific it troughs this error:
`60: SSL certificate problem: self signed certificate in certificate chain`

**Comment by wallin** [comment]
Hey, thanks for reporting. The problem is because your environment doesn't have the latest CA root certificates, which is nothing that you _should_ have to care about when using Castle. I'll fix this by including our cert in the package. In the mean time you could fix it on your end like this:
http://snippets.webaware.com.au/howto/stop-turning-off-curlopt_ssl_verifypeer-and-fix-your-php-config/

**Comment by tankerkiller125** [comment]
Ah ok then I just reported it since I was experiencing the issue on both windows and Linux (something that rarely happens for me)
